---
namespace: dataiku
name: dss
version: 1.0.0
readme: README.md
authors:
- Jean-Bernard Jansen
- Augustin Ardon
description: Dataiku DSS ansible collection
license:
- Apache 2.0
tags: ["dataiku", "dss", "data-science-studio"]
dependencies: {}
repository: http://dataiku/dataiku-ansible-collection
homepage: https://github.com/dataiku/dataiku-ansible-collection
issues: https://github.com/dataiku/dataiku-ansible-collection/issues
build_ignore:
  - venv
  - idea
