---
- name: Find output directory
  find:
    path: "{{ archive_output }}"
    file_type: directory
  register: unarchive_directory

- name: Prepare compile configuration
  environment: "{{ compile_env_vars }}"
  args:
    chdir: "{{ (unarchive_directory.files | first).path }}"
  command: ./autogen.sh

- name: Configure compilation
  environment: "{{ compile_env_vars }}"
  args:
    chdir: "{{ (unarchive_directory.files | first).path }}"
  command: "./configure --prefix {{ compile_prefix }} {{ compile_options }}"

- name: Make compiler
  environment: "{{ compile_env_vars }}"
  community.general.make:
    chdir: "{{ (unarchive_directory.files | first).path }}"
    params:
      -j:

- name: Make install
  environment: "{{ compile_env_vars }}"
  community.general.make:
    chdir: "{{ (unarchive_directory.files | first).path }}"
    target: install
